package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * AdministradorId generated by hbm2java
 */
public class AdministradorId implements java.io.Serializable {

	private String idAdministrador;
	private String nombreAdministrador;
	private String idGiro;

	public AdministradorId() {
	}

	public AdministradorId(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public AdministradorId(String idAdministrador, String nombreAdministrador, String idGiro) {
		this.idAdministrador = idAdministrador;
		this.nombreAdministrador = nombreAdministrador;
		this.idGiro = idGiro;
	}

	public String getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public String getNombreAdministrador() {
		return this.nombreAdministrador;
	}

	public void setNombreAdministrador(String nombreAdministrador) {
		this.nombreAdministrador = nombreAdministrador;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdministradorId))
			return false;
		AdministradorId castOther = (AdministradorId) other;

		return ((this.getIdAdministrador() == castOther.getIdAdministrador())
				|| (this.getIdAdministrador() != null && castOther.getIdAdministrador() != null
						&& this.getIdAdministrador().equals(castOther.getIdAdministrador())))
				&& ((this.getNombreAdministrador() == castOther.getNombreAdministrador())
						|| (this.getNombreAdministrador() != null && castOther.getNombreAdministrador() != null
								&& this.getNombreAdministrador().equals(castOther.getNombreAdministrador())))
				&& ((this.getIdGiro() == castOther.getIdGiro()) || (this.getIdGiro() != null
						&& castOther.getIdGiro() != null && this.getIdGiro().equals(castOther.getIdGiro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdAdministrador() == null ? 0 : this.getIdAdministrador().hashCode());
		result = 37 * result + (getNombreAdministrador() == null ? 0 : this.getNombreAdministrador().hashCode());
		result = 37 * result + (getIdGiro() == null ? 0 : this.getIdGiro().hashCode());
		return result;
	}

}
