package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

import java.math.BigInteger;

/**
 * Biometria generated by hbm2java
 */
public class Biometria implements java.io.Serializable {

	private BigInteger idBiometria;
	private Cliente cliente;
	private byte[] huellaDigital01;
	private byte[] huellaDigital02;

	public Biometria() {
	}

	public Biometria(BigInteger idBiometria) {
		this.idBiometria = idBiometria;
	}

	public Biometria(BigInteger idBiometria, Cliente cliente, byte[] huellaDigital01, byte[] huellaDigital02) {
		this.idBiometria = idBiometria;
		this.cliente = cliente;
		this.huellaDigital01 = huellaDigital01;
		this.huellaDigital02 = huellaDigital02;
	}

	public BigInteger getIdBiometria() {
		return this.idBiometria;
	}

	public void setIdBiometria(BigInteger idBiometria) {
		this.idBiometria = idBiometria;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public byte[] getHuellaDigital01() {
		return this.huellaDigital01;
	}

	public void setHuellaDigital01(byte[] huellaDigital01) {
		this.huellaDigital01 = huellaDigital01;
	}

	public byte[] getHuellaDigital02() {
		return this.huellaDigital02;
	}

	public void setHuellaDigital02(byte[] huellaDigital02) {
		this.huellaDigital02 = huellaDigital02;
	}

}
