package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private String idCliente;
	private String nombres;
	private String apellido;
	private String razonSocial;
	private Set biometrias = new HashSet(0);
	private Set giros = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String idCliente, String nombres, String apellido, String razonSocial) {
		this.idCliente = idCliente;
		this.nombres = nombres;
		this.apellido = apellido;
		this.razonSocial = razonSocial;
	}

	public Cliente(String idCliente, String nombres, String apellido, String razonSocial, Set biometrias, Set giros) {
		this.idCliente = idCliente;
		this.nombres = nombres;
		this.apellido = apellido;
		this.razonSocial = razonSocial;
		this.biometrias = biometrias;
		this.giros = giros;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getRazonSocial() {
		return this.razonSocial;
	}

	public void setRazonSocial(String razonSocial) {
		this.razonSocial = razonSocial;
	}

	public Set getBiometrias() {
		return this.biometrias;
	}

	public void setBiometrias(Set biometrias) {
		this.biometrias = biometrias;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

}
