package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * DineroRecibido generated by hbm2java
 */
public class DineroRecibido implements java.io.Serializable {

	private String idDineroIngresado;
	private Giro giro;
	private String dineroCantidad;
	private String nacionalidad;

	public DineroRecibido() {
	}

	public DineroRecibido(String idDineroIngresado, String dineroCantidad) {
		this.idDineroIngresado = idDineroIngresado;
		this.dineroCantidad = dineroCantidad;
	}

	public DineroRecibido(String idDineroIngresado, Giro giro, String dineroCantidad, String nacionalidad) {
		this.idDineroIngresado = idDineroIngresado;
		this.giro = giro;
		this.dineroCantidad = dineroCantidad;
		this.nacionalidad = nacionalidad;
	}

	public String getIdDineroIngresado() {
		return this.idDineroIngresado;
	}

	public void setIdDineroIngresado(String idDineroIngresado) {
		this.idDineroIngresado = idDineroIngresado;
	}

	public Giro getGiro() {
		return this.giro;
	}

	public void setGiro(Giro giro) {
		this.giro = giro;
	}

	public String getDineroCantidad() {
		return this.dineroCantidad;
	}

	public void setDineroCantidad(String dineroCantidad) {
		this.dineroCantidad = dineroCantidad;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

}
