package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Giro generated by hbm2java
 */
public class Giro implements java.io.Serializable {

	private String idGiro;
	private Cliente cliente;
	private Empleados empleados;
	private Pais pais;
	private Sede sede;
	private String idAdministrador;
	private Set dineroRecibidos = new HashSet(0);
	private Set administradors = new HashSet(0);
	private Set tablaNegociacions = new HashSet(0);
	private Set verificacionMontoPermitidos = new HashSet(0);

	public Giro() {
	}

	public Giro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Giro(String idGiro, Cliente cliente, Empleados empleados, Pais pais, Sede sede, String idAdministrador,
			Set dineroRecibidos, Set administradors, Set tablaNegociacions, Set verificacionMontoPermitidos) {
		this.idGiro = idGiro;
		this.cliente = cliente;
		this.empleados = empleados;
		this.pais = pais;
		this.sede = sede;
		this.idAdministrador = idAdministrador;
		this.dineroRecibidos = dineroRecibidos;
		this.administradors = administradors;
		this.tablaNegociacions = tablaNegociacions;
		this.verificacionMontoPermitidos = verificacionMontoPermitidos;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	public String getIdAdministrador() {
		return this.idAdministrador;
	}

	public void setIdAdministrador(String idAdministrador) {
		this.idAdministrador = idAdministrador;
	}

	public Set getDineroRecibidos() {
		return this.dineroRecibidos;
	}

	public void setDineroRecibidos(Set dineroRecibidos) {
		this.dineroRecibidos = dineroRecibidos;
	}

	public Set getAdministradors() {
		return this.administradors;
	}

	public void setAdministradors(Set administradors) {
		this.administradors = administradors;
	}

	public Set getTablaNegociacions() {
		return this.tablaNegociacions;
	}

	public void setTablaNegociacions(Set tablaNegociacions) {
		this.tablaNegociacions = tablaNegociacions;
	}

	public Set getVerificacionMontoPermitidos() {
		return this.verificacionMontoPermitidos;
	}

	public void setVerificacionMontoPermitidos(Set verificacionMontoPermitidos) {
		this.verificacionMontoPermitidos = verificacionMontoPermitidos;
	}

}
