package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * Locutorio generated by hbm2java
 */
public class Locutorio implements java.io.Serializable {

	private String idLocutorio;
	private Empleados empleados;
	private String enviarGiro;
	private String idPais;

	public Locutorio() {
	}

	public Locutorio(String idLocutorio) {
		this.idLocutorio = idLocutorio;
	}

	public Locutorio(String idLocutorio, Empleados empleados, String enviarGiro, String idPais) {
		this.idLocutorio = idLocutorio;
		this.empleados = empleados;
		this.enviarGiro = enviarGiro;
		this.idPais = idPais;
	}

	public String getIdLocutorio() {
		return this.idLocutorio;
	}

	public void setIdLocutorio(String idLocutorio) {
		this.idLocutorio = idLocutorio;
	}

	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	public String getEnviarGiro() {
		return this.enviarGiro;
	}

	public void setEnviarGiro(String enviarGiro) {
		this.enviarGiro = enviarGiro;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

}
