package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Pais generated by hbm2java
 */
public class Pais implements java.io.Serializable {

	private String idPais;
	private String nombrePais;
	private String origen;
	private String destino;
	private String horaFecha;
	private Set giros = new HashSet(0);

	public Pais() {
	}

	public Pais(String idPais) {
		this.idPais = idPais;
	}

	public Pais(String idPais, String nombrePais, String origen, String destino, String horaFecha, Set giros) {
		this.idPais = idPais;
		this.nombrePais = nombrePais;
		this.origen = origen;
		this.destino = destino;
		this.horaFecha = horaFecha;
		this.giros = giros;
	}

	public String getIdPais() {
		return this.idPais;
	}

	public void setIdPais(String idPais) {
		this.idPais = idPais;
	}

	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public String getHoraFecha() {
		return this.horaFecha;
	}

	public void setHoraFecha(String horaFecha) {
		this.horaFecha = horaFecha;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

}
