package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
public class Sede implements java.io.Serializable {

	private String idSede;
	private String nombreSede;
	private Set giros = new HashSet(0);

	public Sede() {
	}

	public Sede(String idSede) {
		this.idSede = idSede;
	}

	public Sede(String idSede, String nombreSede, Set giros) {
		this.idSede = idSede;
		this.nombreSede = nombreSede;
		this.giros = giros;
	}

	public String getIdSede() {
		return this.idSede;
	}

	public void setIdSede(String idSede) {
		this.idSede = idSede;
	}

	public String getNombreSede() {
		return this.nombreSede;
	}

	public void setNombreSede(String nombreSede) {
		this.nombreSede = nombreSede;
	}

	public Set getGiros() {
		return this.giros;
	}

	public void setGiros(Set giros) {
		this.giros = giros;
	}

}
