package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * TablaNegociacion generated by hbm2java
 */
public class TablaNegociacion implements java.io.Serializable {

	private String idComicion;
	private Giro giro;
	private String origen;
	private String destino;
	private String vigenciaGiro;
	private String flete;
	private String comicion;
	private String idBanco;

	public TablaNegociacion() {
	}

	public TablaNegociacion(String idComicion) {
		this.idComicion = idComicion;
	}

	public TablaNegociacion(String idComicion, Giro giro, String origen, String destino, String vigenciaGiro,
			String flete, String comicion, String idBanco) {
		this.idComicion = idComicion;
		this.giro = giro;
		this.origen = origen;
		this.destino = destino;
		this.vigenciaGiro = vigenciaGiro;
		this.flete = flete;
		this.comicion = comicion;
		this.idBanco = idBanco;
	}

	public String getIdComicion() {
		return this.idComicion;
	}

	public void setIdComicion(String idComicion) {
		this.idComicion = idComicion;
	}

	public Giro getGiro() {
		return this.giro;
	}

	public void setGiro(Giro giro) {
		this.giro = giro;
	}

	public String getOrigen() {
		return this.origen;
	}

	public void setOrigen(String origen) {
		this.origen = origen;
	}

	public String getDestino() {
		return this.destino;
	}

	public void setDestino(String destino) {
		this.destino = destino;
	}

	public String getVigenciaGiro() {
		return this.vigenciaGiro;
	}

	public void setVigenciaGiro(String vigenciaGiro) {
		this.vigenciaGiro = vigenciaGiro;
	}

	public String getFlete() {
		return this.flete;
	}

	public void setFlete(String flete) {
		this.flete = flete;
	}

	public String getComicion() {
		return this.comicion;
	}

	public void setComicion(String comicion) {
		this.comicion = comicion;
	}

	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

}
