package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * VerificacionMontoPermitido generated by hbm2java
 */
public class VerificacionMontoPermitido implements java.io.Serializable {

	private VerificacionMontoPermitidoId id;
	private Giro giro;

	public VerificacionMontoPermitido() {
	}

	public VerificacionMontoPermitido(VerificacionMontoPermitidoId id) {
		this.id = id;
	}

	public VerificacionMontoPermitido(VerificacionMontoPermitidoId id, Giro giro) {
		this.id = id;
		this.giro = giro;
	}

	public VerificacionMontoPermitidoId getId() {
		return this.id;
	}

	public void setId(VerificacionMontoPermitidoId id) {
		this.id = id;
	}

	public Giro getGiro() {
		return this.giro;
	}

	public void setGiro(Giro giro) {
		this.giro = giro;
	}

}
