package co.edu.campusucc.sd.modelos;
// Generated 18/05/2020 09:27:51 PM by Hibernate Tools 5.4.7.Final

/**
 * VerificacionMontoPermitidoId generated by hbm2java
 */
public class VerificacionMontoPermitidoId implements java.io.Serializable {

	private String idCliente;
	private String nombre;
	private String apellido;
	private String idGiro;

	public VerificacionMontoPermitidoId() {
	}

	public VerificacionMontoPermitidoId(String idCliente) {
		this.idCliente = idCliente;
	}

	public VerificacionMontoPermitidoId(String idCliente, String nombre, String apellido, String idGiro) {
		this.idCliente = idCliente;
		this.nombre = nombre;
		this.apellido = apellido;
		this.idGiro = idGiro;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getIdGiro() {
		return this.idGiro;
	}

	public void setIdGiro(String idGiro) {
		this.idGiro = idGiro;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VerificacionMontoPermitidoId))
			return false;
		VerificacionMontoPermitidoId castOther = (VerificacionMontoPermitidoId) other;

		return ((this.getIdCliente() == castOther.getIdCliente()) || (this.getIdCliente() != null
				&& castOther.getIdCliente() != null && this.getIdCliente().equals(castOther.getIdCliente())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getIdGiro() == castOther.getIdGiro()) || (this.getIdGiro() != null
						&& castOther.getIdGiro() != null && this.getIdGiro().equals(castOther.getIdGiro())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdCliente() == null ? 0 : this.getIdCliente().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getIdGiro() == null ? 0 : this.getIdGiro().hashCode());
		return result;
	}

}
